### ISSUE TITLE
dockered VarScan2 issue

### ISSUE THREAD

**Issue by gianfilippo** [bioinform/somaticseq#84]
Hi,

I have to report also an  issue with VarScan2. The run did not complete.

It did create the normal and tumor pileup files, then it fails

The error is
^[[31mFATAL:  ^[[0m Unable to handle docker:///:/mnt uri: failed to get SHA of docker:///:/mnt: unable to parse image name docker:///:/mnt: invalid reference format

Can you please look into it ?

Thanks

**Comment by ltfang-bina** [comment]
Yeah, the script that converted old docker command to singularity script went wrong. I fixed it manually so now hopefully it works.
I don't use singularities internally, so the scripts with singularities are more likely to have errors.

**Comment by ltfang-bina** [comment]
For dockers, the `makeSomaticScripts.py` script/command is working quite well. In the next month or two, I'll probably extend a "docker or singularities" options to that, and retire those legacy .sh scripts.

**Comment by gianfilippo** [comment]
Hi,

thanks for the fix!! 
it seems to be ok now. I will wait for the run to complete and if ok I will close the issue

Best

**Comment by gianfilippo** [comment]
Hi,

I am still getting an error with VarScan2 (see below).  I should mention that I modified your code to run with Slurm directives.
Anyway, I was able to find some similar reports. It seems that this error may be related to concurrent 'use' of singularity cache (https://github.com/hpcng/singularity/issues/4555).

Is this a problem you have seem before or others have reported ? 

Unable to handle docker://djordjeklisic/sbg-varscan2:v1 uri: unable to build: conveyor failed to get: no descriptor found for reference "bf0727087446514ec77d99f7a40fbb43316dcb95f2f516fda6ceedde28f308fd"

Thanks

**Comment by gianfilippo** [comment]
Hi,

according to the singularity blog, this problem can be solved by building the .sif once, before going into any parallel processing. Then 'referring' to it as needed for parallel computations.

Nevertheless, what I do not understand is why I am having this issue only with VarScan2 and not then other callers.

Anyway, right now, if I rerun the varScan2 scripts that fail, eventually they complete without errors. 

Thanks!
